INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('MyFace', 'Social Media', 5000, "December 1st", "December 2nd");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('FaceSpace', 'Social Media', 50, "December 3rd", "December 4th");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('ePort', 'Online Utility', 539284, "December 5th", "December 6th");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Exsy', 'Online Shop', 10, "December 7th", "December 8th");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Belp', 'Search', 109238, "May 1st", "May 2nd");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Sudoku', 'Game', 5983, "May 3rd", "May 4th");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Fall of Dooty', 'Game', 3092384, "May 5th", "May 6ht");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Ober', 'Taxi Hailing', 2, "May 7th", "May 8th");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Clean House', 'House Cleaning', 123, "May 9th", "May 10th");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Movers', 'Moving', 345, "May 11th", "May 12th");

INSERT INTO users (name, age) VALUES ("Bob", 225);
INSERT INTO users (name, age) VALUES ("Steve", 22);
INSERT INTO users (name, age) VALUES ("Sara", 25);
INSERT INTO users (name, age) VALUES ("Holt", 21);
INSERT INTO users (name, age) VALUES ("Drew", 30);
INSERT INTO users (name, age) VALUES ("Rachel", 61);
INSERT INTO users (name, age) VALUES ("Fred", 61);
INSERT INTO users (name, age) VALUES ("Susan", 55);
INSERT INTO users (name, age) VALUES ("Andy", 32);
INSERT INTO users (name, age) VALUES ("Elliott", 24);
INSERT INTO users (name, age) VALUES ("Joe", 22);
INSERT INTO users (name, age) VALUES ("Matt", 16);
INSERT INTO users (name, age) VALUES ("Amanda", 22);
INSERT INTO users (name, age) VALUES ("Benny", 1);
INSERT INTO users (name, age) VALUES ("Wolf", 25);
INSERT INTO users (name, age) VALUES ("Brian", 40);
INSERT INTO users (name, age) VALUES ("James", 20);
INSERT INTO users (name, age) VALUES ("Katie", 20319);
INSERT INTO users (name, age) VALUES ("Catie", 102938);
INSERT INTO users (name, age) VALUES ("Sean", 50);

INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (234, 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10293, 19, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (102938, 18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20983, 17, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 16, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4534, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (098, 13, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8947, 12, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (348, 11, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4389, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (408, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (132, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4985, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12398, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12039, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (36, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90458, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (093, 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4983, 19, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (91823, 18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 17, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (938, 16, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (19283, 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1238, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9238, 13, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1238, 12, 9);
